import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navbar";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body
          className="m-10"
        >
          <NavBar />
          <div className="m-8">
            {children}
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
