import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navbar";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/themeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body
          className="flex justify-center"
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="w-[1200px]">
              <div className="my-10">
                <NavBar />
              </div>
              <div className="m-24">
                {children}
              </div>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
